config/routes.rb
Rails.application.routes.draw do

  root to:  'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :index]
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
  get 'relationships/create'
  get 'relationships/destroy'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor:remember_token

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :birthday,  presence: true
  validates :gender, presence: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  has_many :pictures, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :image, IconUploader

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? Bcrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
   BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
   SecureRandom::urlsafe_base64
  end

  def remember
   self.remember_token = User.new_token
   update_attribute(:remember_digest,User.digest(remember_token))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end
  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
      @user = User.new(user_params)
      if @user.save
        redirect_to user_path(@user.id), notice: "アカウント作成しました"
      else
        render :new if @user.invalid?
      end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end

  def confirm
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,:birthday, :gender,
                                 :password_confirmation, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gender_view(type)
  case type
  when 1
      "男"
    when 2
      "女"
    when 3
      "その他"
    else
      puts "非表示"
  end
  end
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% content_for :title do %>
<h1>編集する</h1>
<% end %>
<% if @user.errors.any? %>
  <% content_for :error do %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count, "件") %>のエラーがあります。<%= @user.name %></h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
    </div>
  <% end %>
<% end %>

<%= form_with(model: @user, local: true ) do |f| %>

<div class="image_small">
  <% if @user.image.present? %>
   <p><%= image_tag(@user.image.url, :size => "50x50") %></p>
  <% else %>
   <p><%= image_tag("default.png", :size => "50x50") %></p>
  <% end %>
  <%= f.file_field :image, class:"image_upload" %>
  <%= f.hidden_field :image_cache %>
</div>
  <%= f.text_field :UserName, placeholder: 'お名前', class: "form-control has-error" %>
  <%= f.email_field :email, placeholder: 'メールアドレス', class: "form-control has-error" %>
  <%= f.password_field :password, placeholder: 'パスワード' %><br>
  <div class="birthday">
  <%= f.label :birthday, "お誕生日", class:'control-label' %><br>
  <%= raw sprintf(
            f.date_select(
              :birthday,
              use_month_numbers: true,
              start_year: 1930,
              end_year: (Time.now.year - 18),
              default: Date.new(1989, 1, 1),
              date_separator: '%s'),
              '年 ', '月 ') + '日生まれ' %>
  </div>

  <div class= "gender_parent">
    <%= f.label :gender, "性別", class:'gender_select', class: "control-label" %><br>
    <span><%= f.radio_button :gender, 1, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "男", class:"input-group-addon has-error" %></span>
    <span><%= f.radio_button :gender, 2, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "女", class:"input-group-addon has-error" %></span>
    <span><%= f.radio_button :gender, 3, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "カスタム", class:"input-group-addon has-error" %></span>
  </div>
    <%= f.submit "編集する", class:'button' %>
<% end %>

  <%= link_to "投稿一覧画面にもどる", pictures_path, class:'button login' %>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
    <li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
  <% end %>
<% end %>

app/views/users/new.html.erb
<% content_for :title do %>
  <h1>新規アカウントを作成</h1>
  <br>
  <p>簡単に登録できます</p>
<% end %>
<% if @user.errors.any? %>
  <% content_for :error do %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count, "件") %>のエラーがあります。<%= @user.name %></h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
    </div>
  <% end %>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>

  <%= f.text_field :name, placeholder: 'お名前', class: "form-control has-error" %>
  <%= f.email_field :email, placeholder: 'メールアドレス', class: "form-control has-error" %>
  <div class="birthday">
  <%= f.label :birthday, "お誕生日", class:'control-label' %><br>
  <%= raw sprintf(
            f.date_select(
              :birthday,
              use_month_numbers: true,
              start_year: 1930,
              end_year: (Time.now.year - 18),
              default: Date.new(1989, 1, 1),
              date_separator: '%s'),
              '年 ', '月 ') + '日生まれ' %>
  </div>
  <div class= "gender_parent">
    <%= f.label :gender, "性別", class:'gender_select', class: "control-label" %><br>
    <span><%= f.radio_button :gender, 1, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "男", class:"input-group-addon has-error" %></span>
    <span><%= f.radio_button :gender, 2, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "女", class:"input-group-addon has-error" %></span>
    <span><%= f.radio_button :gender, 3, class:"input-group-addon has-error" %></span>
    <span><%= f.label :gender, "カスタム", class:"input-group-addon has-error" %></span>
  </div>
    <%= f.password_field :password, placeholder: 'パスワード', class: "form-control has-error" %>
    <%= f.password_field :password_confirmation, placeholder: '確認用パスワード', class: "form-control has-error" %>
    <%= f.submit "アカウントを作成", class:'button' %>
<% end %>

app/views/users/show.html.erb
<% content_for :title do %>
  <div class="clearfix profile_bar">
    <div class="profile_name"><%= @user.name %>のページ
    <div class="profile_icon">
      <% if @user.image.present? %>
       <p><%= image_tag(@user.image.url, :size => "50x50") %></p>
      <% else %>
       <p><%= image_tag("default.png", :size => "50x50") %></p>
      <% end %>
    </div>
    </div>
  </div>

<% end %>

<div class="profile_content">
  <table>
    <tr>
      <th>メールアドレス:</th><td><%= @user.email %></td>
    </tr>
    <tr>
      <th>誕生日:</th><td><%= @user.birthday %></td>
    </tr>
    <tr>
      <th>性別:</th><td><%= gender_view(@user.gender) %></td>
    </tr>
  </table>
</div>

<% if logged_in? %>
  <%= link_to "編集する", edit_user_path(current_user), class:'button login' %>
  <%= link_to "投稿一覧画面へ", pictures_path, class:'button login' %>
<% else %>
  <%= link_to "ログインする", new_session_path, class:"button login" %>
<% end %>