config/routes.rb
Rails.application.routes.draw do

  root to:  'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :index]
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
  get 'relationships/create'
  get 'relationships/destroy'
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image_or_content, presence: true
  attr_accessor :action_required

  private
  def image_or_content
    image.presence or content.presence
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      ender :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit' 
      picture_path
    end
  end
end

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url:choose_new_or_edit) do |form| %>

<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @picture.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form.text_area :content, class:'form_control', rows: 10, placeholder: "コメントを書く"%>
<div class="image">
  <%if @picture.image.url.present?%>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%end%>
    <%= form.file_field :image, class:"image_upload" %>
    <%= form.hidden_field :image_cache %>
</div>



<div class="submit">
  <%= form.submit "登録する", class:"button" %>
</div>

<div class="navbar">
  <%= link_to "投稿一覧画面にもどる", pictures_path %>
</div>

<% end %>

app/views/pictures/confirm.html.erb
<% content_for :title do %>
  <h1>確認画面</h1>
<% end %>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>

  <div class="text">
    <div class="title">本文</div>

    <%= @picture.content %>
    <%= form.hidden_field :content %>
  </div>

  <div class="image">
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="submit">
    <%= form.submit "投稿する", class:"button" %>
    <%= form.submit "戻る", name: "back", class:"button" %>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<% content_for :title do %>
<h1>写真を編集する</h1>
<% end %>
<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert <%= bootstrap_class_for(key) %><%= value %></div>
<% end %>
<div class="top-image">

  <h2><%= current_user.name %>のページ</h2>
</div>

<div class="timeline">


  <article class="posts">
    <div class="link_to_new">
      <%= link_to new_picture_path, method: :get do %>
        <i class="fa fa-plus">新しく投稿する</i>
      <% end %>
    </div>

      <% @pictures.each do |picture| %>
      <div class="post_content">
        <div class="picture_name">
          <% if picture.user.image.present? %>
            <%= image_tag(picture.user.image.url, :size => "50x50") %>
          <% else %>
             <%= image_tag("default.png", :size => "50x50") %>
          <% end %>
          <span class="user_name"><%= picture.user.name %></span>
          <span class="created_time"><%= picture.created_at %></span>
        </div>
        <div class="picture_content"><%= picture.content %></div>
        <div class="picture_image">
          <% if picture.image? %>
            <%= image_tag picture.image.url%>
          <% end %>
        </div>

      <div class="post_nav">
        <%= link_to '新規投稿', new_picture_path(picture.id), method: :get %>

        <%= link_to '写真投稿の編集', edit_picture_path(picture.id), method: :get  %>


        <%= link_to '写真投稿の消去', picture_path(picture), method: :delete, data: { confirm: '本当に消去しますか?' } %>


      </div>
    </div>
    <% end %>
  </article>
</div>

app/views/pictures/new.html.erb
<% content_for :title do %>
<h1>新規投稿</h1>
<% end %>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<% content_for :title do %>
  <h1>コメント</h1>
<% end %>

<div class="text">
  <div class="title">本文</div>
  <%= @picture.content %>
</div>
<div class="image">
  <%= image_tag @picture.image.url %>
</div>

<div class="submit">
  <%= link_to '編集する', edit_picture_path(@picture), class:"button" %>
  <%= link_to '戻る', pictures_path, class:"button" %>
</div>