config/routes.rb
Rails.application.routes.draw do

  root to:  'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :index]
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :conversations do
    resources :messages
  end
  get 'relationships/create'
  get 'relationships/destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',  'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
      <header>
        <div class ="clearfix loggedout_menubar_container">
          <div class="logo_parent">
            <%= link_to("Fb", new_session_path, {class: "logo_child"})%>
          </div>
          <div class="menu_login_container">
            <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id), {class: "profile"} %>
            <%= link_to "Logout", new_session_path, class: "logout", method: :delete%>
          

            <% else %>
            <%= link_to "Sign up", new_user_path, {class: "signup"} %>
            <%= link_to "Login", new_session_path, {class: "loginin"} %>
            <% end %>
          </div>
        </div>

      </header>
       <li><%= link_to 'ユーザー一覧', users_path if logged_in? %></li>
      <% flash.each do |key, value| %>
      <div class="alert <%= bootstrap_class_for(key) %>" ><%= value %></div>
      <% end %>
    <div class="content">
      <div class="title_parent">
        <div class="title_child">
          <%= yield :title %>
        </div>
      </div>
    <%= yield :error %>
    <div class="form-content">
      <%= yield %>
    </div>
    </div>
      <footer>
        <div class ="footer_container">
        <p>運営会社Fb株式会社</p>
        <p>© 2020 Copyright KY Corp.</p>
        </div>
      </footer>
    </div>
  </body>
</html>